default: &default
  adapter: postgis
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: mlit-stations-api_development

test:
  <<: *default
  database: mlit-stations-api_test

production:
  <<: *default
  database: mlit-stations-api_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
